### ISSUE TITLE
Please remove this repositorie from github

### ISSUE THREAD

**Issue by harnishdesign** [raniamhelmy/SimonePersonalPortfolio#2]
Hi,

Please remove this Simone Personal Portfolio template from github.
Simone Template is our premium template. You can not it represent source as public in github.

Simone Template available here: https://themeforest.net/item/simone-personal-portfolio-template/28476751

Hope, you are understand.
Thanks.

**Comment by raniamhelmy** [comment]
Hi

1st of all, thank you for your feedback
2nd, Maybe it was a mistake but I never said that this template was my design, all I did was just trying to mimic the original design to improve & enhance my HTML and CSS Skills by using one of most spectacular templates found on the internet,  which fortunately was yours. So, please accept my apology for not mentioning your original template link earlier and I'm pretty sure that your design was much better than mine in professionalism and performance.

Have a nice day
Sincerely,
